version: '3.4'

services:
  ordersapiapp:
    container_name: application
    image: ${DOCKER_REGISTRY-}ordersapiapp
    build:
      context: .
      dockerfile: OrdersApiApp/Dockerfile


  database:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=OrderDb
    ports:
      - 5432:5432

    networks:
      - internal


networks:
  internal:
    driver: bridge
